### ISSUE TITLE
When I end the heist ! 

### ISSUE THREAD

**Issue by subhampro** [DvScriptsSK/dv-yacht#4]
![image](https://user-images.githubusercontent.com/33375250/235371176-adeb846a-a973-4a16-989b-55b4feab1e43.png)
![image](https://user-images.githubusercontent.com/33375250/235371182-651b98ce-bba6-4714-a2e5-7b8719461634.png)

**Comment by DvScriptsSK** [comment]
Hello, this issue is being fixed and update  will be available today

**Comment by subhampro** [comment]
FIXED By my own !! ```   local distance = #(GetEntityCoords(GetPlayerPed(src)) - Config.startlocation)``

**Comment by subhampro** [comment]
Thanks btw :)
